from . import res_partner
from . import res_company
from . import res_config_settings
from . import account_move
from . import product_product
from . import account_payment
from . import crm_lead
from . import sale_order
from . import sale_order_line
