# -*- coding: utf-8 -*-
from odoo import _, api, fields, models
from odoo.exceptions import UserError
from odoo.tools import format_datetime


class CompanycamPhoto(models.Model):
    _name = 'companycam.photo'
    _description = 'Job Site Photo or Video'
    _inherit = ['mail.thread', 'image.mixin']
    _order = 'captured_at desc, id desc'
    _mail_post_access = 'read'

    name = fields.Char(string='Title', compute='_compute_name', store=True, readonly=False)
    description = fields.Text(string='Caption')
    media_type = fields.Selection(
        [('photo', 'Photo'), ('video', 'Video')],
        string='Type', required=True, default='photo', index=True)
    # Optional: a quick photo can be taken first and filed in a project later.
    # Deleting a project keeps its photos (they become "without project").
    project_id = fields.Many2one(
        'project.project', string='Project', index=True,
        ondelete='set null', tracking=True)
    partner_id = fields.Many2one(related='project_id.partner_id', string='Customer')
    company_id = fields.Many2one(
        'res.company', string='Company', compute='_compute_company_id', store=True, index=True,
        default=lambda self: self.env.company)
    user_id = fields.Many2one(
        'res.users', string='Captured by', default=lambda self: self.env.user,
        index=True, tracking=True)
    captured_at = fields.Datetime(
        string='Captured on', required=True, default=fields.Datetime.now, index=True)
    tag_ids = fields.Many2many('companycam.tag', string='Tags')
    starred = fields.Boolean(string='Starred', tracking=True)
    capture_uid = fields.Char(copy=False, index=True, readonly=True,
                              help='Identifier generated by the camera, prevents duplicate uploads.')

    # Location stamp
    latitude = fields.Float(digits=(10, 7))
    longitude = fields.Float(digits=(10, 7))
    location_accuracy = fields.Float(string='Accuracy (m)', digits=(10, 1))
    has_location = fields.Boolean(compute='_compute_has_location')
    map_url = fields.Char(string='Map', compute='_compute_has_location')

    # Video (the poster frame is stored in image_1920)
    video_file = fields.Binary(string='Video', attachment=True)
    video_filename = fields.Char()
    video_mimetype = fields.Char()
    video_duration = fields.Float(string='Duration (s)', digits=(10, 1))
    dual_camera = fields.Boolean(string='Dual camera video')

    # Markup: the original stays in image_1920; the flattened markup is saved apart
    image_annotated = fields.Image(string='Photo with markup', max_width=1920, max_height=1920)
    image_annotated_512 = fields.Image(
        related='image_annotated', string='Markup thumbnail', max_width=512, max_height=512, store=True)
    annotation_json = fields.Text(copy=False)
    has_annotation = fields.Boolean(compute='_compute_has_annotation', store=True)

    @api.depends('media_type', 'captured_at')
    def _compute_name(self):
        for photo in self:
            if photo.name:
                continue
            label = _('Video') if photo.media_type == 'video' else _('Photo')
            when = format_datetime(self.env, photo.captured_at or fields.Datetime.now(), dt_format='short')
            photo.name = f'{label} {when}'

    @api.depends('project_id.company_id')
    def _compute_company_id(self):
        for photo in self:
            photo.company_id = photo.project_id.company_id or photo.company_id or self.env.company

    @api.depends('latitude', 'longitude')
    def _compute_has_location(self):
        for photo in self:
            photo.has_location = bool(photo.latitude or photo.longitude)
            photo.map_url = (
                f'https://www.openstreetmap.org/?mlat={photo.latitude}&mlon={photo.longitude}'
                f'#map=19/{photo.latitude}/{photo.longitude}'
                if photo.has_location else False)

    @api.depends('image_annotated')
    def _compute_has_annotation(self):
        for photo in self:
            photo.has_annotation = bool(photo.image_annotated)

    def _get_display_image_field(self):
        """Field holding the image to show: the markup version wins over the original."""
        self.ensure_one()
        return 'image_annotated' if self.has_annotation else 'image_1920'

    # ------------------------------------------------------------------
    # Actions
    # ------------------------------------------------------------------
    def action_companycam_annotate(self):
        self.ensure_one()
        if self.media_type != 'photo':
            raise UserError(_('Markup is available on photos only.'))
        return {
            'type': 'ir.actions.client',
            'tag': 'tw_companycam.annotate',
            'name': _('Markup'),
            'target': 'fullscreen',
            'params': {'photo_id': self.id},
        }

    def action_companycam_remove_annotation(self):
        self.write({'image_annotated': False, 'annotation_json': False})

    def action_companycam_toggle_star(self):
        for photo in self:
            photo.starred = not photo.starred

    def action_companycam_create_gallery(self):
        if not self:
            raise UserError(_('Select at least one photo or video to share.'))
        projects = self.project_id
        gallery = self.env['companycam.gallery'].create({
            'name': projects.name if len(projects) == 1 else _('Shared photos'),
            'project_id': projects.id if len(projects) == 1 else False,
            'photo_ids': [fields.Command.set(self.ids)],
        })
        return {
            'type': 'ir.actions.act_window',
            'res_model': 'companycam.gallery',
            'res_id': gallery.id,
            'view_mode': 'form',
            'views': [(False, 'form')],
            'target': 'current',
        }

    def companycam_report_groups(self):
        """[(project or False, photos)] for the PDF report; photos without project come last."""
        groups = [(project, self.filtered(lambda p, pr=project: p.project_id == pr)) for project in self.project_id]
        unsorted = self.filtered(lambda p: not p.project_id)
        if unsorted:
            groups.append((False, unsorted))
        return groups

    def action_companycam_print_report(self):
        return self.env.ref('tw_companycam.action_report_companycam_photos').report_action(self)
